app = "railmod"
primary_region = "sjc"

[build]
  dockerfile = "deploy/Dockerfile"

[mounts]
  source = "redisdata"
  destination = "/data"

[experimental]
  auto_rollback = true

[defaults]
  region = "sjc"
